#!/usr/bin/env python3
"""Run, verify and visualise a Z3 plan for the River Crossing puzzle.

Usage:
    python checker.py cross_river.py

It imports the student's solver module, asks it for a plan over the horizon
N defined inside that module, independently re-checks the plan in plain
Python, and then draws it on the terminal.
"""

import argparse
import importlib.util
import os
import pathlib
import sys


def local_python():
    """Return the project-local venv interpreter if one exists; otherwise None."""
    project_root = pathlib.Path(__file__).resolve().parent
    for base in [project_root / 'z3env', project_root / '.venv']:
        candidate = base / 'bin' / 'python'
        if candidate.exists():
            return str(candidate)
    return None


def ensure_runtime():
    """Re-exec under the project-local venv when available, so the exact command works."""
    venv_python = local_python()
    if venv_python and not sys.executable.endswith('/z3env/bin/python'):
        os.execv(venv_python, [venv_python, __file__, *sys.argv[1:]])


def load_module(path):
    """Import a Python module from a given filepath."""
    module_path = pathlib.Path(path)
    spec = importlib.util.spec_from_file_location(module_path.stem, module_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load module from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def verify(states, moves, NAMES, ENTITIES, CARGO, CONFLICTS, FARMER):
    """Re-check the plan in plain Python. Returns a list of complaints."""
    errors = []
    n = len(moves)

    if not all(states[0][e] for e in ENTITIES):
        errors.append("t=0: not everyone starts on the left bank")
    if any(states[n][e] for e in ENTITIES):
        errors.append(f"t={n}: not everyone ended on the right bank")

    for t in range(n):
        here, nxt, carried = states[t], states[t + 1], moves[t]

        if nxt[FARMER] == here[FARMER]:
            errors.append(f"step {t}: the farmer did not cross")
        if carried is not None:
            if here[carried] != here[FARMER]:
                errors.append(f"step {t}: {NAMES[carried]} boarded from the wrong bank")
            if nxt[carried] == here[carried]:
                errors.append(f"step {t}: {NAMES[carried]} boarded but did not cross")
        for e in CARGO:
            if e != carried and nxt[e] != here[e]:
                errors.append(f"step {t}: {NAMES[e]} moved on its own")

    for t, st in enumerate(states):
        for a, b in CONFLICTS:
            if st[a] == st[b] and st[FARMER] != st[a]:
                bank = "left" if st[a] else "right"
                errors.append(f"t={t}: {NAMES[a]} and {NAMES[b]} left alone on the {bank} bank")
    return errors


BANK_W = 32
MID_W = 28


def _bank(state, on_left, ENTITIES, NAMES):
    who = [NAMES[e] for e in ENTITIES if state[e] == on_left]
    return '  '.join(who) if who else '-'


def render_terminal(states, moves, NAMES, ENTITIES, FARMER):
    n = len(moves)
    river = '~' * 22

    print()
    print(f"     {'LEFT BANK':^{BANK_W}} {'':^{MID_W}} {'RIGHT BANK':^{BANK_W}}")
    print("     " + "-" * BANK_W + " " * (MID_W + 2) + "-" * BANK_W)

    for t, st in enumerate(states):
        left, right = _bank(st, True, ENTITIES, NAMES), _bank(st, False, ENTITIES, NAMES)
        print(f"t={t}  {left:^{BANK_W}}|{river:^{MID_W}}|{right:^{BANK_W}}")

        if t < n:
            carried = moves[t]
            cargo = f"Farmer + {NAMES[carried]}" if carried else "Farmer alone"
            going_right = st[FARMER] and not states[t + 1][FARMER]
            arrow = f"--{cargo}-->" if going_right else f"<--{cargo}--"
            print(f"     {'':^{BANK_W}}|{arrow:^{MID_W}}|")

    print()
    print(f"  Solved in {n} crossings.")


def main():
    ensure_runtime()

    ap = argparse.ArgumentParser(description="Check a plan generated by a Z3 river-crossing model.")
    ap.add_argument("module", help="Path to the solver module, e.g. cross_river.py")
    args = ap.parse_args()

    mod = load_module(args.module)
    n = getattr(mod, "N")

    plan = mod.solve(n)
    if plan is None:
        print(f"Unsatisfiable: no plan uses {n} crossings.")
        print("(Try raising N in the solver module.)")
        return
    print(f"Satisfiable! A plan exists with a horizon of {n}.")

    states, moves = plan
    errors = verify(states, moves, mod.NAMES, mod.ENTITIES, mod.CARGO, mod.CONFLICTS, mod.FARMER)
    if errors:
        print("\n  PLAN FAILED INDEPENDENT VERIFICATION:")
        for e in errors:
            print(f"    - {e}")
    else:
        print("  Plan independently verified: safe at every step.")

    render_terminal(states, moves, mod.NAMES, mod.ENTITIES, mod.FARMER)


if __name__ == '__main__':
    main()
